feat: implement habits part 2
habits-together/app pull request #141
Opened 2024-12-08 21:37 UTC by owengretzinger

2024-12-08 21:37 UTC, owengretzinger commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/habits-together/app/141?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#141** <a href="https://app.graphite.dev/github/pr/habits-together/app/141?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/habits-together/app/141?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#140** <a href="https://app.graphite.dev/github/pr/habits-together/app/140?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-10 02:15 UTC, AnkushSarkar10 requested changes
bitch ass

2024-12-10 02:15 UTC, AnkushSarkar10 commented on src/core/hooks/use-selected-theme.tsx
> -    console.log('theme', theme);
remove

2024-12-10 02:15 UTC, AnkushSarkar10 commented on src/core/get-translucent-color.tsx
> +export function getTranslucentColor(colorHexValue: string, opacity: number) {
mention opacity bw 0-1

2024-12-10 02:21 UTC, AnkushSarkar10 approved these changes

2024-12-10 02:21 UTC, merged